export const inheritence = {
	CSSStyleSheet: 'StyleSheet',
	CustomEvent: 'Event',
	DOMException: 'Error',
	Document: 'Node',
	DocumentFragment: 'Node',
	Element: 'Node',
	File: 'Blob',
	HTMLDivElement: 'HTMLElement',
	HTMLDocument: 'Document',
	HTMLElement: 'Element',
	HTMLHeadElement: 'HTMLElement',
	HTMLHtmlElement: 'HTMLElement',
	HTMLImageElement: 'HTMLElement',
	HTMLStyleElement: 'HTMLElement',
	HTMLTemplateElement: 'HTMLElement',
	HTMLUnknownElement: 'HTMLElement',
	Image: 'HTMLElement',
	MediaQueryList: 'EventTarget',
	Node: 'EventTarget',
	ShadowRoot: 'DocumentFragment',
	Window: 'EventTarget',
} as const
